### ISSUE TITLE
Can't Authorize Web Indexing API

### ISSUE THREAD

**Issue by AntoineKM** [harlan-zw/request-indexing#14]
### Describe the bug

When i click the "[Authorize Web Indexing API](https://requestindexing.com/auth/google-indexing)" button
<img width="390" alt="image" src="https://github.com/harlan-zw/request-indexing/assets/54948363/f261650d-1cf3-49d1-bb78-3b540b24e945">

I'm getting this error:
<img width="801" alt="image" src="https://github.com/harlan-zw/request-indexing/assets/54948363/603fc8a6-a6e3-4076-9a22-fdd7e2f06e69">

**Comment by harlan-zw** [comment]
Hi, thank you for the issue. The website is currently at maximum usage limits for using Google's Web Indexing API, I'll try and resolve when possible but it may take 1-2 days.
