### ISSUE TITLE
Vercel KV - daily request limit exceeded

### ISSUE THREAD

**Issue by DavidDeSloovere** [harlan-zw/request-indexing#2]
### Describe the bug

Just got an error after registering via Google and coming back to the site.
You are probably trying to keep the costs low, which I respect. 
Maybe a custom error message like "This application has exceeded it's daily quota, try again tomorrow." ?

`ERR max daily request limit exceeded. Limit: 3000, Usage: 3000. See https://vercel.com/docs/storage/vercel-kv/vercel-kv-error-codes for details, command was: ["get","user:user-xxxxxxxxx:me.json"]`

**Comment by harlan-zw** [comment]
Hi @DavidDeSloovere, thanks for reporting this. I was migrating the database from Vercel to Upstash and it instantly destroyed my daily limit. Should be all working now :)
