### ISSUE TITLE
429 errors on authorizing web indexing api

### ISSUE THREAD

**Issue by remihuigen** [harlan-zw/request-indexing#22]
### Describe the bug

I've connected my Google Account, and site properties are showing up in the dashbaord. Whenever I open a site, and try to authorize the indexing API, it returns a 429

```
{
"statusCode": 429,
"statusMessage": "Oops, looks like we have too many users right now. Please try again later.",
"stack": []
}
```

Also, there's a broken link in the permissions card at  "account page"

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. 

Google is cracking down on this API, to protect end users accounts I've disabled the API for the time being until I decide on the solution. 

Sorry for the poor UX, just have had limited time to sort it out.

**Comment by remihuigen** [comment]
Thats a shame 😫 Are you considering integrating the request indexing api in some way into Nuxt SEO pro? Because that alone would be reason to buy that during the presale 

For prerender / static apps, its quite anoying to request indexing manually after each build
