### ISSUE TITLE
Unknown Bug

### ISSUE THREAD

**Issue by baptiste-faure1811** [harlan-zw/request-indexing#7]
### Describe the bug

I think there might be a bug, yesterday 70% of my website was marked as indexed by Google and today it is down to 3%. Paths from the Indexed Page tab are also in the Non-indexed Pages tab, and I have so many 'results' pages as shown in the screenshots below. Am I doing something wrong ?

As you can see on the screenshots, the '/blog' is shown on both the index and non-indexed tabs, and so many negative pages at the bottom.

Let me know if I can do anything to help.

<img width="1920" alt="Screenshot 2024-02-26 at 08 03 23 (2)" src="https://github.com/harlan-zw/request-indexing/assets/59772651/191b3320-e926-4012-a13b-3273ecb9a0ad">
<img width="1920" alt="Screenshot 2024-02-26 at 08 03 18 (2)" src="https://github.com/harlan-zw/request-indexing/assets/59772651/3acbd011-a652-4afb-a32f-00da3a95099b">
<img width="1920" alt="Screenshot 2024-02-26 at 08 04 08 (2)" src="https://github.com/harlan-zw/request-indexing/assets/59772651/31809e50-eaf3-4cba-8760-d8b643abe0a1">

**Comment by harlan-zw** [comment]
Hi @baptiste-faure1811, thanks for making an issue.

I honestly have no idea what's going on here, I think may be a data conflict or something. This may sound dumb but the easiest solution is probably to delete your account and sign up again. There's not any data you'll lose that won't immediately be generated again.

Alternatively, you can email me with your user id (found in the account side panel) so I can dig deeper. If the delete + sign up doesn't fix it, I may need read access to the GSC properly.

My email is harlan@harlanzw.com either way
